
package eu.comvantage.domainconfiguration.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.1
 * Thu May 15 18:19:18 CEST 2014
 * Generated source version: 2.6.1
 */

@XmlRootElement(name = "addDomainSystemParameter", namespace = "http://domainconfiguration.comvantage.eu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addDomainSystemParameter", namespace = "http://domainconfiguration.comvantage.eu/")

public class AddDomainSystemParameter {

    @XmlElement(name = "param")
    private eu.comvantage.domainconfiguration.data.DomainSystemParameter param;

    public eu.comvantage.domainconfiguration.data.DomainSystemParameter getParam() {
        return this.param;
    }

    public void setParam(eu.comvantage.domainconfiguration.data.DomainSystemParameter newParam)  {
        this.param = newParam;
    }

}

