
package eu.comvantage.domainconfiguration.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.1
 * Thu May 15 18:19:19 CEST 2014
 * Generated source version: 2.6.1
 */

@XmlRootElement(name = "addDomainSource", namespace = "http://domainconfiguration.comvantage.eu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addDomainSource", namespace = "http://domainconfiguration.comvantage.eu/")

public class AddDomainSource {

    @XmlElement(name = "source")
    private eu.comvantage.domainconfiguration.data.DomainSourceDetail source;

    public eu.comvantage.domainconfiguration.data.DomainSourceDetail getSource() {
        return this.source;
    }

    public void setSource(eu.comvantage.domainconfiguration.data.DomainSourceDetail newSource)  {
        this.source = newSource;
    }

}

