
package eu.comvantage.domainconfiguration.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.1
 * Thu May 15 18:19:19 CEST 2014
 * Generated source version: 2.6.1
 */

@XmlRootElement(name = "getAllDomainRoles", namespace = "http://domainconfiguration.comvantage.eu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllDomainRoles", namespace = "http://domainconfiguration.comvantage.eu/")

public class GetAllDomainRoles {


}

