
package eu.comvantage.domainconfiguration.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.1
 * Thu May 15 18:19:18 CEST 2014
 * Generated source version: 2.6.1
 */

@XmlRootElement(name = "getDomainSourcesByType", namespace = "http://domainconfiguration.comvantage.eu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDomainSourcesByType", namespace = "http://domainconfiguration.comvantage.eu/")

public class GetDomainSourcesByType {

    @XmlElement(name = "type")
    private java.lang.String type;

    public java.lang.String getType() {
        return this.type;
    }

    public void setType(java.lang.String newType)  {
        this.type = newType;
    }

}

