
package eu.comvantage.domainconfiguration.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.1
 * Thu May 15 18:19:18 CEST 2014
 * Generated source version: 2.6.1
 */

@XmlRootElement(name = "getDomainSystemParametersByKey", namespace = "http://domainconfiguration.comvantage.eu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDomainSystemParametersByKey", namespace = "http://domainconfiguration.comvantage.eu/")

public class GetDomainSystemParametersByKey {

    @XmlElement(name = "key")
    private java.lang.String key;

    public java.lang.String getKey() {
        return this.key;
    }

    public void setKey(java.lang.String newKey)  {
        this.key = newKey;
    }

}

